name: "test-docker-build"
on: 
  #push:
  #  branches:
  #    - main
  workflow_dispatch: # The repository will be scanned on demand


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.RT_URL }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.RT_ACCESS_TOKEN }}
          DOCKER_IMAGE_NAME: $JF_URL/morielp-docker-local/hello-frog:1
          JFROG_CLI_BUILD_NAME: myBuild
          JFROG_CLI_BUILD_NUMBER: 1
         

          # Basic authentication credentials
          ## JF_USER: ${{ secrets.JF_USER }}
          ## JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: morielp-docker-local/hello-frog:1  

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          jf docker scan
          jf audit --watches "all_cves"
          # Publish build info
          jf rt bp 
          jf bs 
